### PR TITLE
v1.1.2

### PR DESCRIPTION
**Pull request by bugsounet**
* Update installer dependency:
  * esbuild
* Fix: rotation config (@thomo)

### CODE REVIEW

**Comment by giovamec** [comment]
Dear @bugsounet , In the past I use your MMM-NewPIR  "Turn on display with click mouse or touch screen" as I suggest in 2020.
now having installed everything and updated my entire touch mirror I noticed that the module no longer exists. the functionality is only reported in EXT-Screen.
Would it be possible to reinsert them into the MMM-Pir module too?
Sorry for writing here, but I haven't found a way to add a comment to suggest improvements.
Thank you very much for your valuable work
Giovamec

**Comment by bugsounet** [comment]
Hi,

I assume that i have reported minimal things on this module ;)
but I can Add it on next release ;)

**Comment by giovamec** [comment]
yes, I can imagine,
however I think it is very useful to use even without installing the entire MMM-GoogleAssistant part.
I look forward to the next update with impatience and pleasure. I can give you feedback on how it works as soon as I try it
thank you very much Giovamec

**Comment by giovamec** [comment]
Dear @bugsounet, for now, when I use the module in mode: 1 all the modules turn off correctly but the monitor remains on, it is not a real monitor off. instead, when I use mode 10, the monitor turns off but when it is reactivated on the pir sensor, even with the correct wrandrForceRotation mode ="90", the screen is reactivated with the right rotation but with the 640x480 resolution. in other words it does not return to the previous screen mode in full hd. I'm using a Pi4B 4GB with Wayland. Suggestions? tnks Giovamec

**Comment by giovamec** [comment]
Dear, for now, when I use the module in mode: 1 all the modules turn off but the monitor remains on, it is not a real monitor off. instead, when I use mode 10, the monitor turns off but when it is reactivated on the pir sensor, even with the correct wrandrForceRotation mode ="90", the screen is reactivated with the right rotation but with the 640x480 resolution. in other words it does not return to the previous screen mode in full hd. I'm using a Pi4B 4GB with Wayland. Suggestions? tnks Giovamec

**Comment by Eyesallin** [comment]
Hi
I'm completely new to this.
I have a Pi 5 on Magicmirror.
I installed MMM-Pir when ir runs the countdown but it displays 2 errors top of screen, pir has no effect countdown expires and turns of the screen.
Errors :
image

**Comment by bugsounet** [comment]
@giovamec : I will try to save screen resolution before turn off and report it when turn on
I will back to you for testing

@Eyesallin: Open an issue on MM² forum, thx

**Pull request merged**
