### PR TITLE
Mode 8 - switch relay

### PR DESCRIPTION
**Pull request by kwerner72**
Added missing relay mode.
With new mode '8' it is possible to switch a relay depending on screen state.

### CODE REVIEW

**Comment by bugsounet** [comment]
Thanks for this PR !
good job ;)

**Comment by bugsounet** [comment]
@kwerner72

I search to use `gpiozero` library

can you help me to debug this and see if it's works like mode 8?
because i have no relay (and i don't use it)

```
import gpiozero
from signal import pause
import argparse, sys, time

parser = argparse.ArgumentParser(
    description='Activate/Desactivate a relay from GPIO for MMM-Pir',
    epilog="©bugsounet 2024"
)

def gpio_check(x):
    x = int(x)
    if x < 1 or x > 29:
        raise argparse.ArgumentTypeError("GPIO must be between 1 and 29")
    return x

def relay_check(x):
    x = int(x)
    if x < 0 or x > 1:
        raise argparse.ArgumentTypeError("Relay state must be 0 (Off) or 1 (On)")
    return x

parser.add_argument("-g", "--gpio", help="Define GPIO", type=gpio_check, required=True)
parser.add_argument("-s", "--state", help="Relay state ON/OFF", type=relay_check, required=True)

args = parser.parse_args(None if sys.argv[1:] else ['-h'])

GPIO = int(args.gpio)
STATE = int(args.state)

print("DEBUG GPIO:", GPIO)
print("DEBUG STATE:", STATE)

relay = gpiozero.OutputDevice(GPIO, active_high=False, initial_value=None)
#relay = gpiozero.OutputDevice(GPIO, active_high=True, initial_value=None)

def set_relay(status):
  if status == 1:
    print("Setting relay: ON")
    relay.on()
  else:
    print("Setting relay: OFF")
    relay.off()

try:
  set_relay(STATE)
  print("DEBUG: ---> State", relay.value)
except Exception as e:
  print("Error:", e)
```

Using helping sample:

`python test3.py -s 0 -g 13`

 * `s` is the realy state wanted -> `0` for turn off relay, `1` for turn on relay
 * `g` is the gpio number

Thanks for your help

**Comment by kwerner72** [comment]
Yes, I'll test it.
Unfortunately my SD card broke and I have to to setup the whole environment from scratch, which will take some days :(
As soon as its up again, I'll give you feedback.

**Comment by bugsounet** [comment]
@sdetweil do you use/have relay for test it ?

**Comment by kwerner72** [comment]
Now I had the chance to test the above code.
Unfortunately it does not work. The code seem to alter the input/output state of the related pin.

The commands below...
- set pin 26 as output
- set ping 26 to low
- set pin 26 to high with test code
- check pin level
- set pin 26 to low with test code
- check pin level -> wrong value
- set pin 26 to low -> error

```
pi@smartmirror:~/MagicMirror $ pinctrl set 26 op
pi@smartmirror:~/MagicMirror $ pinctrl set 26 dl
pi@smartmirror:~/MagicMirror $ python test.py -s 1 -g 26
DEBUG GPIO: 26
DEBUG STATE: 1
Setting relay: ON
DEBUG: ---> State 1
pi@smartmirror:~/MagicMirror $ pinctrl lev 26
1
pi@smartmirror:~/MagicMirror $ python test.py -s 0 -g 26
DEBUG GPIO: 26
DEBUG STATE: 0
Setting relay: OFF
DEBUG: ---> State 0
pi@smartmirror:~/MagicMirror $ pinctrl lev 26
1
pi@smartmirror:~/MagicMirror $ pinctrl set 26 dl
Can't set pin value, not an output
```

**Comment by bugsounet** [comment]
That why, i ask you to test it.

I have tested in a free gpio and I have the same result.
I don't understand whyI just follow [this](https://gpiozero.readthedocs.io/en/stable/api_output.html)

It don't want to set gpio as output, it set only in input :/

**Comment by kwerner72** [comment]
Think I've found the reason, why the test failed: https://raspberrypi.stackexchange.com/questions/148686/raspberry-pi-5-gpiozero

The test code sets the correct pin value, but then resets it right before exiting.
When adding a sleep of e.g. 5 seconds, the pin value stays in the desired state for this amount of time.
So I think gpiozero is working, only the test was wrong ;o)

**Pull request merged**
